### ISSUE TITLE
Incorrect read counts for bin matrix?

### ISSUE THREAD

**Issue by timoast** [r3fang/SnapTools#10]
Hi, I came across what might be a bug in the `add_bmat` function. When I create a 5 kb bin matrix, I found some of the entries in the matrix were zero for some cells, while if I look in the BAM file I used to make the bin x cell matrix there are reads present for those cells in the corresponding region.

For example, using the 10k PBMC dataset from 10x, the following read is present in the BAM downloaded from their website:

```
A00519:57:HG3JCDMXX:2:1442:13566:3693	163	chr1	10058	0	49M	=	10318	288	CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	FFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFF,FFFFFFF::FF,:FF	NM:i:0	MD:Z:49	MC:Z:15S28M7S	AS:i:49	XS:i:49	CR:Z:TTCGGTCTCCGTCAAA	CY:Z:FFFFF:FFFFFFFFF,	CB:Z:TTCGGTCTCCGTCAAA-1	BC:Z:TCTCGACT	QT:Z:F:FFFF:F	GP:i:10057	MP:i:10352	MQ:i:1	RG:Z:atac_v1_pbmc_10k:MissingLibrary:1:HG3JCDMXX:2
```

So cell `TTCGGTCTCCGTCAAA` in the bin `chr1:10001-15000` (if using 5 kb bins).

I ran:

```
snaptools snap-add-bmat --snap-file=atac_v1_pbmc_10k.snap --bin-size-list 5000 --verbose=True
```

To generate a bin x cell matrix. Then in R, I load the snap file:

```r
library(SnapATAC)
atac <- createSnap(file = "/home/stuartt/data/10x_atac/pbmc/bam/atac_v1_pbmc_10k.snap", sample = 'pbmc')
atac <- addBmatToSnap(atac, bin.size = 5000, num.cores = 1)
```

I then extracted the matrix from the snap object to look at the entries, and there is zero recorded for the cell and position for which the BAM line is displayed above:

```r
bmat <- atac@bmat
rownames(bmat) <- atac@barcode
colnames(bmat) <- atac@feature$name

bmat["TTCGGTCTCCGTCAAA", 'chr1:10001-15000']
[1] 0
```

Perhaps I'm not extracting the row and column names properly from the snap file, but I also tried reversing the orders and could not find a combination that gave 1 count for the matrix entry.

I also looked in the fragments file, which agrees with the BAM and not the bin x cell matrix from snaptools, ie this line is present (also from the 10x website):

```
chr1 10067 10334 TTCGGTCTCCGTCAAA-1  1
```

**Comment by r3fang** [comment]
Hi there,


Thanks for trying it out!

in this example, the mapq which is 5th column after `10058` is `0` which indicates this read has low mapping score. Any fragments with mapq less than 30 will be filtered.

```
A00519:57:HG3JCDMXX:2:1442:13566:3693	163	chr1	10058	0	49M	=	10318	288	CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC	FFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFF,FFFFFFF::FF,:FF	NM:i:0	MD:Z:49	MC:Z:15S28M7S	AS:i:49	XS:i:49	CR:Z:TTCGGTCTCCGTCAAA	CY:Z:FFFFF:FFFFFFFFF,	CB:Z:TTCGGTCTCCGTCAAA-1	BC:Z:TCTCGACT	QT:Z:F:FFFF:F	GP:i:10057	MP:i:10352	MQ:i:1	RG:Z:atac_v1_pbmc_10k:MissingLibrary:1:HG3JCDMXX:2
```

10X may have different filtering strategy.
