### ISSUE TITLE
snap-add-pmat naming inconsistancy Warning

### ISSUE THREAD

**Issue by yasserIRCM** [r3fang/SnapTools#17]
Hi there 
I have this problem appearing when running the following command
$ snaptools snap-add-pmat --snap-file possorted_bamwt.snap --peak-file peaks.combinedWT.bed
***** WARNING: File /tmp/tmp9ff841ln has inconsistent naming convention for record:
b'chr13'	64267370	64267591	AAACGAAAGCAACTGG-1

***** WARNING: File /tmp/tmp9ff841ln has inconsistent naming convention for record:
b'chr13'	64267370	64267591	AAACGAAAGCAACTGG-1

**Comment by camiel-m** [comment]
Hi,
I'm having a similar issue. Depending on which sample I run, the line/chromosome returned will be different. In the peaks.combined.bed file there was no b in front of the chromosome identifier. Might this be the cause?

bed:
chr1 | 3061013 | 3061213
chr1 | 3094639 | 3095566
chr1 | 3113486 | 3114089

error:
***** WARNING: File /tmp/tmpukodzuzj has inconsistent naming convention for record:
b'chr10'	13594002	13594363	AAAAAAAAAAAAAAAA

***** WARNING: File /tmp/tmpukodzuzj has inconsistent naming convention for record:
b'chr10'	13594002	13594363	AAAAAAAAAAAAAAAA

**Comment by r3fang** [comment]
Hi this is an issue caused by python 3.6 or above. I am aware of this issue for a while but did not have a time to fix it. Would it be possible to used python 2.7 for now? I will try to fix once I got sometime


--
Rongxin Fang, Ren Lab
Ludwig Cancer Research
Bioinformatics Ph.D. Student
University of California, San Diego

**Comment by yasserIRCM** [comment]
Hi there

I confirm that it was due to running Snaptool on python 3.7. I have run it again on python 2.7 and it worked flowlessly

thanks

**Comment by r3fang** [comment]
Thanks for letting me know.

**Comment by Dominic7227** [comment]
Hi Dr. Fang,

I also came into this issue when using 'snap-tools snap-add-pmat' under python 3.7. My snap-tools version is 1.4.8. I notice that snap-tools over 1.4 should work with python 3.

The reporting warning is identical to the issue reported here. It appears one 'b' in front of ever read.
***** WARNING: File /tmp/tmp9qreqg_y has inconsistent naming convention for record:
b'chr1' 47904687        47904739        AAAAAAGAACCTAATT

***** WARNING: File /tmp/tmp9qreqg_y has inconsistent naming convention for record:
b'chr1' 47904687        47904739        AAAAAAGAACCTAATT

Could please help me with it? Thanks a lot!
