### ISSUE TITLE
memory issue with creating snap-pre

### ISSUE THREAD

**Issue by danielgchen** [r3fang/SnapTools#22]
Hi,

I am trying to use the snaptools processing pipeline with my paired end fastq file (around 40 GB for R1 and 43 GB for R2) and ended with a bam file that was 104 GB in size, however everytime I try to move onto the next step and run snap-pre the program prints out 'Killed' after using up all of the memory, is there a possible way to fix this or a workaround? My system has a limit of 125 GB of memory for RAM and then another 125 GB for swap, but the command eats up all of it. The program ran for around 100 minutes. Thanks!

Here's my code:

```
'snaptools snap-pre' +\
                ' --input-file=' + bam_file_name +\
                ' --output-snap=merged.snap' +\
                ' --genome-name=hg19' +\
                ' --genome-size=hg19.chrom.sizes' +\
                ' --min-mapq=30' +\
                ' --min-flen=0' +\
                ' --max-flen=1000' +\
                ' --keep-chrm=TRUE' +\
                ' --keep-single=TRUE' +\
                ' --keep-secondary=False' +\
                ' --overwrite=True' +\
                ' --max-num=1000000' +\
                ' --min-cov=100' +\
                ' --verbose=True'
```

Do you think setting a tmp folder would free some of this memory, I have around 1 TB of free storage so I think it should be fine for the program?

**Comment by r3fang** [comment]
hello,

I am sorry for this bug. I have long been wising to solve the memory issue. I think the best way to proceed with current version is to cut the bam file into small chunks and generate multiple `snap` files and combine these `snap` files in the downstream analysis. 

 1) sort the bam file (with the read name as prefix) based on the read name.
2) split the bam file into multiple smaller bam files with each containing less than 20000 unique cell barcodes
3) generate snap file for each bam file
4) follow this example which performs integrative analysis of multiple snap files.
https://github.com/r3fang/SnapATAC/blob/master/examples/10X_PBMC_15K/README.md

**Comment by danielgchen** [comment]
Ah I see, those steps sound good. Thank you!

**Comment by qing5579** [comment]
Hello, I have met the same problem. I wonder that whether the barcode information is required to split bam files? Or is it possible to split bam files arbitrarily, as long as each small bam file contains less than 20000 uniq Barcodes?
