### ISSUE TITLE
add_bmat to snap file that already have bmat

### ISSUE THREAD

**Issue by lhqing** [r3fang/SnapTools#3]
https://github.com/r3fang/SnapTools/blob/a909c427e2c8b8648b015ee4e549c0f9483a4739/snaptools/add_bmat.py#L119

This line indicate when add bmat to snap file that already have bmat, we should use --snap-del
But I can't find --snap-del in the CLI. 

Thank you!

**Comment by r3fang** [comment]
This function was in the old version but get removed in the latest version. Will ass it soon

**Comment by lhqing** [comment]
OK, thank you for the wonderful work!

**Comment by r3fang** [comment]
add `snap-del` now

**Comment by hjack123** [comment]
I dont know what the session name is?

**Comment by r3fang** [comment]
the session name is AM

```
[r3fang@tscc-login2 SnapATAC]$ snaptools snap-del -h
usage: snaptools snap-del [-h] --snap-file SNAP_FILE --session-name
                          SESSION_NAME

optional arguments:
  -h, --help            show this help message and exit

required inputs:
  --snap-file SNAP_FILE
                        snap file. (default: None)
  --session-name SESSION_NAME
                        session to be deleted in snap file. 'AM': cell-by-bin
                        matrix. All cell-by-bin matrices will be removed.
                        'PM': cell-by-peak matrix. 'GM': cell-by-gene matrix.
                        (default: None)
```

--
Rongxin Fang
Ph.D. Student, Ren Lab
Ludwig Institute for Cancer Research
University of California, San Diego
